restart_interval = 10
workers = 1
per_core = false

[workload]
type = "network"
server = true
address = "223.42.0.1"
target_port = 1337
connections_static = 100
connections_dyn_max = 1000
preempt = true
