FROM registry.fedoraproject.org/fedora:42

RUN dnf install -y \
    rust \
    cargo \
    clippy \
    rustfmt \
    # for stub \
    nasm \
    # for script jit \
    llvm-devel \
    zlib-devel \
    libxml2-devel \
    libstdc++-static

ADD ./ /berserker/

WORKDIR /berserker/

RUN cargo fmt --check

RUN cargo clippy -- -D warnings

RUN cargo build -r

RUN cargo test

RUN nasm -f elf64 -o stub.o stub.asm && ld -o stub stub.o
