name: Main berserker CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: make

      - run: make build-berserker-network

      - name: Get tag
        run: |
          TAG="$(make tag)"
          echo "TAG=$TAG" >> "$GITHUB_ENV"

      - name: Retag and push berserker to rhacs-eng
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: berserker
          dst-image: quay.io/rhacs-eng/qa:berserker-${{ env.TAG }}
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Retag and push berserker to stackrox-io
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: berserker
          dst-image: quay.io/stackrox-io/berserker:${{ env.TAG }}
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

      - name: Retag and push berserker-network to rhacs-eng
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: berserker-network
          dst-image: quay.io/rhacs-eng/qa:berserker-network-${{ env.TAG }}
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Retag and push berserker-network to stackrox-io
        uses: stackrox/actions/images/retag-and-push@v1
        with:
          src-image: berserker-network
          dst-image: quay.io/stackrox-io/berserker:network-${{ env.TAG }}
          username: ${{ secrets.QUAY_STACKROX_IO_RW_USERNAME }}
          password: ${{ secrets.QUAY_STACKROX_IO_RW_PASSWORD }}

