name: Main berserker CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy

      - name: Run tests
        run: cargo test

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: make

        #- name: Login to quay.io/stackrox-io
        #  uses: docker/login-action@v2
        #  with:
        #    registry: quay.io
        #    username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
        #    password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Get tag
        run: |
          TAG="$(make tag)"
          echo "TAG=$TAG" >> $GITHUB_ENV 

      - name: Retag and push stackrox-io
        uses: stackrox/actions/images/retag-and-push@jv-ROX-19084-github-action-to-retag-and-push-images
        with:
          src-image: berserker
          dst-image: quay.io/rhacs-eng/qa:berserker-${{ env.TAG }}
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

